---
- name: intall nginx offline 
  hosts: all 
  become: yes 
  tasks:
    - name: update cache
      apt:
        name:
          - git
          - build-essential
          - libpcre3
          - libpcre3-dev
          - zlib1g
          - zlib1g-dev
          - libssl-dev
          - libgd-dev
          - libxml2
          - libxml2-dev
          - uuid-dev
        state: present
            
    - name: copy
      copy:
        src: nginx-1.20.2.tar.gz
        dest: /tmp/nginx-1.20.2.tar.gz

    - name: Extract the tar file
      unarchive:
        src: /tmp/nginx-1.20.2.tar.gz
        dest: /home/siva/
        copy: false
        extra_opts: [--strip-components=1]
        
    - name: Change directory to Nginx source code
      shell: cd /home/siva/nginx-1.20.2/

    - name: Configure Nginx
      shell: |
        ./configure \
          --prefix=/etc/nginx \
          --conf-path=/etc/nginx/nginx.conf \
          --error-log-path=/var/log/nginx/error.log \
          --http-log-path=/var/log/nginx/access.log \
          --pid-path=/run/nginx.pid \
          --sbin-path=/usr/sbin/nginx \
          --with-http_ssl_module \
          --with-http_v2_module \
          --with-http_stub_status_module \
          --with-http_realip_module \
          --with-file-aio \
          --with-threads \
          --with-stream \
          --with-stream_ssl_preread_module
        make
        make install

    - name: Check Nginx version and build information
      command: /usr/sbin/nginx -V
      register: nginx_version

    - name: Check Nginx version and build information
      debug:
        var: nginx_version
      when: nginx_version.rc == 0

    - name: create the systemd file
      copy:
        src: /home/siva/nginx.service
        dest: /lib/systemd/system/nginx.service

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: enabled systemd
      systemd:
        name: nginx
        enabled: yes

    - name: create the systemd file
      copy:
        src: /home/siva/tet/nginx
        dest: /etc/logrotate.d/nginx
        
    - name: start nginx service
      systemd:
        name: nginx
        state: started

#https://facsiaginsa.com/nginx/how-to-install-nginx-from-source